update=2017-12-12 13:57:28
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=switches
LibName4=relays
LibName5=motors
LibName6=transistors
LibName7=conn
LibName8=linear
LibName9=regul
LibName10=74xx
LibName11=cmos4000
LibName12=adc-dac
LibName13=memory
LibName14=xilinx
LibName15=microcontrollers
LibName16=dsp
LibName17=microchip
LibName18=analog_switches
LibName19=motorola
LibName20=texas
LibName21=intel
LibName22=audio
LibName23=interface
LibName24=digital-audio
LibName25=philips
LibName26=display
LibName27=cypress
LibName28=siliconi
LibName29=opto
LibName30=atmel
LibName31=contrib
LibName32=valves
LibName33=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName34=C:/Program Files/KiCad/share/kicad/library/74xx
LibName35=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName36=C:/Program Files/KiCad/share/kicad/library/actel
LibName37=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName38=C:/Program Files/KiCad/share/kicad/library/allegro
LibName39=C:/Program Files/KiCad/share/kicad/library/Altera
LibName40=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName41=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName42=C:/Program Files/KiCad/share/kicad/library/atmel
LibName43=C:/Program Files/KiCad/share/kicad/library/audio
LibName44=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName45=C:/Program Files/KiCad/share/kicad/library/bbd
LibName46=C:/Program Files/KiCad/share/kicad/library/bosch
LibName47=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName48=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName49=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName50=C:/Program Files/KiCad/share/kicad/library/conn
LibName51=C:/Program Files/KiCad/share/kicad/library/contrib
LibName52=C:/Program Files/KiCad/share/kicad/library/cypress
LibName53=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName54=C:/Program Files/KiCad/share/kicad/library/device
LibName55=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName56=C:/Program Files/KiCad/share/kicad/library/diode
LibName57=C:/Program Files/KiCad/share/kicad/library/display
LibName58=C:/Program Files/KiCad/share/kicad/library/dsp
LibName59=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName60=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName61=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName62=C:/Program Files/KiCad/share/kicad/library/gennum
LibName63=C:/Program Files/KiCad/share/kicad/library/graphic_symbols
LibName64=C:/Program Files/KiCad/share/kicad/library/hc11
LibName65=C:/Program Files/KiCad/share/kicad/library/infineon
LibName66=C:/Program Files/KiCad/share/kicad/library/intel
LibName67=C:/Program Files/KiCad/share/kicad/library/interface
LibName68=C:/Program Files/KiCad/share/kicad/library/intersil
LibName69=C:/Program Files/KiCad/share/kicad/library/ir
LibName70=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName71=C:/Program Files/KiCad/share/kicad/library/leds
LibName72=C:/Program Files/KiCad/share/kicad/library/LEM
LibName73=C:/Program Files/KiCad/share/kicad/library/linear
LibName74=C:/Program Files/KiCad/share/kicad/library/logic_programmable
LibName75=C:/Program Files/KiCad/share/kicad/library/maxim
LibName76=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName77=C:/Program Files/KiCad/share/kicad/library/memory
LibName78=C:/Program Files/KiCad/share/kicad/library/microchip
LibName79=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName80=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName81=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName82=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName83=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName84=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName85=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName86=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName87=C:/Program Files/KiCad/share/kicad/library/modules
LibName88=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName89=C:/Program Files/KiCad/share/kicad/library/motorola
LibName90=C:/Program Files/KiCad/share/kicad/library/motors
LibName91=C:/Program Files/KiCad/share/kicad/library/msp430
LibName92=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName93=C:/Program Files/KiCad/share/kicad/library/nxp
LibName94=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName95=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName96=C:/Program Files/KiCad/share/kicad/library/opto
LibName97=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName98=C:/Program Files/KiCad/share/kicad/library/philips
LibName99=C:/Program Files/KiCad/share/kicad/library/power
LibName100=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName101=C:/Program Files/KiCad/share/kicad/library/powerint
LibName102=C:/Program Files/KiCad/share/kicad/library/pspice
LibName103=C:/Program Files/KiCad/share/kicad/library/references
LibName104=C:/Program Files/KiCad/share/kicad/library/regul
LibName105=C:/Program Files/KiCad/share/kicad/library/relays
LibName106=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName107=C:/Program Files/KiCad/share/kicad/library/RFSolutions
LibName108=C:/Program Files/KiCad/share/kicad/library/sensors
LibName109=C:/Program Files/KiCad/share/kicad/library/silabs
LibName110=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName111=C:/Program Files/KiCad/share/kicad/library/stm8
LibName112=C:/Program Files/KiCad/share/kicad/library/stm32
LibName113=C:/Program Files/KiCad/share/kicad/library/supertex
LibName114=C:/Program Files/KiCad/share/kicad/library/switches
LibName115=C:/Program Files/KiCad/share/kicad/library/texas
LibName116=C:/Program Files/KiCad/share/kicad/library/transf
LibName117=C:/Program Files/KiCad/share/kicad/library/transistors
LibName118=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName119=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName120=C:/Program Files/KiCad/share/kicad/library/valves
LibName121=C:/Program Files/KiCad/share/kicad/library/video
LibName122=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName123=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName124=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName125=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName126=C:/Program Files/KiCad/share/kicad/library/zetex
LibName127=C:/Program Files/KiCad/share/kicad/library/Zilog
